site_name: juan-perez-p-application
site_description: Java Spring boot app with prometheus and loki integration

nav:
  - Home: index.md
  - Bit√°cora del Experimento: Bitacora.md

plugins:
  - techdocs-core
